matrix:
  - name: Markdown
    expect_match: false
    apsell:
      lang: en
      d: en_US
      camel-case: true
      ignore-case: true
    dictionary:
      wordlists:
      - .wordlist.txt
      output: wordlist.dic
      encoding: utf-8
    pipeline:
    - pyspelling.filters.markdown:
        markdown_extensions:
        - markdown.extensions.extra:
    - pyspelling.filters.html:
        comments: false
        attributes:
        - alt
        ignores:
        - ':matches(code, pre)'
        - 'code'
        - 'pre'
        - 'blockquote'
    sources:
    - '**/*.md'
  - name: Rust
    apsell:
      lang: en
      d: en_US
      camel-case: true
      ignore-case: true
    dictionary:
      wordlists:
      - .wordlist.txt
      output: wordlist.dic
      encoding: utf-8
    pipeline:
      - pyspelling.filters.url:
    sources:
    - '**/*.rs'
  - name: TypeScript
    apsell:
      lang: en
      d: en_US
      camel-case: true
      ignore-case: true
    dictionary:
      wordlists:
      - .wordlist.txt
      output: wordlist.dic
      encoding: utf-8
    pipeline:
      - pyspelling.filters.url:
    sources:
    - '**/*.ts'
