[package]
name = "musdk-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", features = ["full", "fold"] }
quote = "1"
proc-macro2 = "1.0"
proc-macro-error = "1.0"
