[package]
name = "todo"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21.0"
musdk = { path = "../../../../sdk/musdk" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.94"
