[package]
name = "mu-cli"
version = "0.1.0"
rust-version = "1.56"
edition = "2021"
repository = "https://github.com/muprotocol/mu"
description = "Mu CLI"
license = "Apache-2.0"
default-run = "mu"

[[bin]]
name = "mu"
path = "src/bin/mu.rs"
doc = false

[dependencies]
mu_stack = { path = "../mu_stack" }
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
thiserror = "1.0"
shellexpand = "2.1"
dirs = "3.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"

anchor-client = "0.25"
spl-token = "^3.3"
solana-clap-utils = "~1.10"
solana-cli-config = "~1.10"
solana-account-decoder = "1.10"
solana-remote-wallet = "~1.10"
spl-associated-token-account = "^1.0"
uriparse = "0.6"

marketplace = { path = "../marketplace/programs/marketplace/", features = [
    "no-entrypoint",
] }
