[package]
name = "mu-cli"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/muprotocol/mu"
description = "Mu CLI"
license = "Apache-2.0"
default-run = "mu"

[[bin]]
name = "mu"
path = "src/bin/mu.rs"
doc = false

[dependencies]
async-trait = "0.1"
clap = { version = "4.1", features = ["derive"] }
anyhow = "1.0"
thiserror = "1.0"
shellexpand = "3"
dirs = "4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1"
rust-embed = "6.4"
rand = "0.8"
tokio = "1.0"
tokio-util = "0.7"
ctrlc = "3.2"
uriparse = "0.6"
beau_collector = "0.2"
byte-unit = { version = "4.0", default-features = false, features = ["serde"] }
reqwest = "0.11"

anchor-client = "0.26"
spl-token = "3"
solana-clap-utils = "1"
solana-cli-config = "1"
solana-account-decoder = "1"
solana-remote-wallet = "1"
spl-associated-token-account = "1"

marketplace = { path = "../marketplace/programs/marketplace/", features = [ "no-entrypoint"] }
mu-runtime = { path = "../rust-libs/runtime" }
mu-gateway = { path = "../rust-libs/gateway" }
mu_stack = { path = "../rust-libs/mu_stack" }
musdk-common = { path = "../sdk/common" }
mu-db = { path = "../rust-libs/db" }
