name: my_stack
version: 0.1
services:
  - type: KeyValueTable
    name: my_db
  - type: Function
    name: my_function
    binary: http://localhost:8080/test-function.wasm
    runtime: wasi1.0
    memory_limit: 256MiB
    env: {}
  - type: Gateway
    name: my_gateway
    endpoints:
      /req:
        - method: post
          route_to: my_function.greet_user
      /req/{name}:
        - method: get
          route_to: my_function.greet_path_user
