[features]
seeds = false
[programs.localnet]
marketplace = "2MZLka8nfoAf1LKCCbgCw5ZXfpMbKGDuLjQ88MNMyti2"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test"
deploy-empty = "npx ts-node ./scripts/cmd-deploy-empty.ts"
initialize-program = "npx ts-node ./scripts/cmd-initialize-program.ts"
