[features]
seeds = false
[programs.localnet]
marketplace = "H7eDBkyrr5jLcjmNmyTbDo45sS6U6MvHx6fFGiF9AL8r"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test"
deploy-uninitialized = "npx ts-node ./scripts/cmd-deploy-uninitialized.ts"
deploy-empty = "npx ts-node ./scripts/cmd-deploy-empty.ts"
deploy-test-stack = "npx ts-node ./scripts/cmd-deploy-test-stack.ts"
initialize-mu = "npx ts-node ./scripts/cmd-initialize-mu.ts"
setup-cli-dev = "npx ts-node ./scripts/cmd-setup-cli-dev.ts"
run-many-nodes = "npx ts-node ./scripts/cmd-run-many-nodes.ts"
