[features]
seeds = false
[programs.localnet]
marketplace = "9YNk2WSJ4rXsvJFM2teXJhJ2LZL3XDUPP2FAiNuGsFtx"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/hamid/.config/solana/id.json"

[scripts]
test = "npm run test"
deploy-empty = "npx ts-node ./scripts/cmd-deploy-empty.ts"
