import Head from 'next/head'
import React from "react";
import dynamic from "next/dynamic";

export default function Home() {
    const ProviderList = dynamic(() => import('@/components/providers/ProviderList'), {
        ssr: false
    })

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main data-testid="content">
                <ProviderList />
            </main>
        </>
    )
}
