[package]
name = "executor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer = "2.3"
tokio = { version = "1.0", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"]}
serde = "1"
tokio-serde = {version = "0.8", features = ["bincode"]}
futures = "0.3"

[lib]
name = "mu"

[[bin]]
path = "src/main.rs"
name = "mu-executor"