[package]
name = "executor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer = { git = "https://github.com/wasmerio/wasmer" }
wasmer-wasi = { git = "https://github.com/wasmerio/wasmer" }
tokio = { version = "1.0", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"]}
serde = "1"
tokio-serde = {version = "0.8", features = ["bincode"]}
futures = "0.3"
pin-project = "1.0"
rand = "0.8"
uuid = { version = "1.1.2", features = ["fast-rng", "v4", "serde"]}
anyhow = "1.0"
thiserror = "1.0"

[lib]
name = "mu"

[[bin]]
path = "src/main.rs"
name = "mu-executor"
