[package]
name = "executor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer = { git = "https://github.com/wasmerio/wasmer" }
wasmer-wasi = { git = "https://github.com/wasmerio/wasmer" }
tokio = { version = "1.0", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
tokio-serde = { version = "0.8", features = ["bincode"] }
bytes = "1.2"
serde = "1"
serde_json = "1"
serde_yaml = "0.9"
futures = "0.3"
pin-project = "1.0"
async-trait = "0.1"
rand = "0.8"
anyhow = "1.0"
thiserror = "1.0"
reqwest = "0.11"
tokio_mailbox_processor = { path = "../../tokio_mailbox_processor" }

[lib]
name = "mu"

[[bin]]
path = "src/main.rs"
name = "mu-executor"
