[package]
name = "musdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
musdk-common = { path = "../common" }
musdk-derive = { path = "../derive" }

thiserror = "1.0"
