on: [pull_request]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.63.0
          override: true
          components: rustfmt, clippy
          target: wasm32-wasi
      - name: Check style
        run: cargo fmt -- --check
        working-directory: executor
      - name: Run Lints
        run: cargo clippy -- -D warnings
        working-directory: executor
      - name: Run tests
        run: cargo test --verbose
        working-directory: executor
        env:
          RUST_BACKTRACE: 1
