name: test
on:
  pull_request:
env:
  LLVM_SYS_120_PREFIX: /usr/lib/llvm-12/
jobs:
  lint_and_test:
    runs-on: [self-hosted, linux, X64]
    strategy:
      matrix:
        dir:
          - executor
          - cli
          - rust-libs/mailbox_processor
          - marketplace
          - rust-libs/mu_stack
          - sdk
          - rust-libs/common
          - rust-libs/runtime
          - rust-libs/gateway
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            cli/target/
            executor/target/
            mailbox_processor/target/
            marketplace/target/
            mu_stack/target/
            sdk/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential curl libssl-dev libudev-dev pkg-config zlib1g-dev clang cmake make language-pack-en libclang-common-12-dev llvm-12-dev protoc
      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.65.0
          override: true
          components: rustfmt, clippy
          target: wasm32-wasi
      - name: Check style
        run: cargo fmt -- --check
        working-directory: ${{ matrix.dir }}
      - name: Run Lints
        run: cargo clippy --no-deps --all-targets --tests -- -D warnings
        working-directory: ${{ matrix.dir }}
      - name: Run tests
        run: cargo test --verbose
        working-directory: ${{ matrix.dir }}
        env:
          RUST_BACKTRACE: 1
