name: test
on:
  pull_request:
jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            cli/target/
            executor/target/
            mailbox_proceessor/target/
            marketplace/target/
            mu_stack/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.63.0
          override: true
          components: rustfmt, clippy
          target: wasm32-wasi
      - name: Check style
        run: cargo fmt -- --check
        working-directory: executor, cli
      - name: Run Lints
        run: cargo clippy -- -D warnings
        working-directory: executor, cli
      - name: Run tests
        run: cargo test --verbose
        working-directory: executor, cli
        env:
          RUST_BACKTRACE: 1