name: Build and Upload on Amazon S3

on:
  push:
    
env:
  LLVM_SYS_120_PREFIX: /usr/lib/llvm-12/
  RUST_BACKTRACE: full

jobs:
  lint_and_test:
    runs-on: [self-hosted, linux, X64]
    strategy:
      matrix:
        dir:
          - executor
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Restore dependencies cache
        uses: actions/cache@v3
        if: success()
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            executor/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl libssl-dev libudev-dev pkg-config zlib1g-dev clang cmake make language-pack-en libclang-common-12-dev llvm-12-dev protobuf-compiler
      
      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.65.0
          override: true
          components: rustfmt, clippy
          target: wasm32-wasi

      - name: Check style
        run: cargo fmt -- --check
        working-directory: ${{ matrix.dir }}

      - name: Build Release
        if: success()
        run: cargo build --release
        working-directory: ${{ matrix.dir }}
      
      - name: Save dependencies cache
        uses: actions/cache@v3
        if: success()
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            executor/target/ 
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

  deploy:
    runs-on: [self-hosted, linux, X64]
    
    strategy:
      matrix:
        dir:
          - executor
    
    steps:
      - name: Checkout to master
        uses: actions/checkout@master

      - name: Upload to S3
        uses: koraykoska/s3-upload-github-action@master
        env:
          FILE: executor/target/release/mu-executor
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
